<?php
/**
 * Orangepill WooCommerce Blocks Integration (PR-WC-BLOCKS-COMPATIBILITY-V1)
 *
 * Registers the Orangepill payment method with the WooCommerce Blocks payment
 * method registry so it appears on the Cart and Checkout Blocks (WC 8.0+).
 *
 * Architecture: this class is a RENDERER registration only.
 * - No new AJAX endpoints introduced (all 4 existing endpoints reused)
 * - No process_payment() modifications
 * - No webhook handler modifications
 * - All canonical PHP authority (process_payment, webhook handler, transients) unchanged
 *
 * The React component (build/blocks.js) submits _orangepill_intent_id and
 * _orangepill_execution_type via paymentMethodData, which WC Blocks passes to
 * process_payment() via $_POST — exactly as classic shortcode checkout does.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

use Automattic\WooCommerce\Blocks\Payments\Integrations\AbstractPaymentMethodType;

class OP_Blocks_Integration extends AbstractPaymentMethodType {

    /**
     * Payment method name — must match OP_Payment_Gateway::$id.
     */
    protected $name = 'orangepill';

    /**
     * Load settings from WP options.
     */
    public function initialize() {
        $this->settings = get_option( 'woocommerce_orangepill_settings', array() );
    }

    /**
     * Return true when the gateway is fully configured and enabled.
     * Mirrors OP_Payment_Gateway::is_available() — both must agree.
     */
    public function is_active() {
        return ( $this->settings['enabled'] ?? 'no' ) === 'yes'
            && ! empty( $this->settings['api_key'] )
            && ! empty( $this->settings['integration_id'] )
            && ! empty( $this->settings['merchant_id'] );
    }

    /**
     * Register the Blocks JS bundle and return its script handle.
     *
     * build/blocks.asset.php is auto-generated by @wordpress/scripts and contains
     * the correct dependency list + content hash for cache-busting.
     */
    public function get_payment_method_script_handles() {
        $asset_file = ORANGEPILL_WC_PLUGIN_DIR . 'build/blocks.asset.php';
        $asset_data = file_exists( $asset_file )
            ? require $asset_file
            : array( 'dependencies' => array(), 'version' => ORANGEPILL_WC_VERSION );

        $deps = array_unique( array_merge(
            $asset_data['dependencies'],
            array(
                'wc-blocks-registry',
                'wc-blocks-checkout',
                'wp-element',
                'wp-html-entities',
                'wp-i18n',
            )
        ) );

        wp_register_script(
            'orangepill-blocks',
            ORANGEPILL_WC_PLUGIN_URL . 'build/blocks.js',
            $deps,
            $asset_data['version'],
            true
        );

        wp_set_script_translations( 'orangepill-blocks', 'orangepill-wc' );

        return array( 'orangepill-blocks' );
    }

    /**
     * Data passed to the React component via window.orangepillBlocksConfig.
     *
     * Nonce: single shared 'orangepill_wc_checkout' nonce — matches all existing
     * check_ajax_referer() calls in OP_Payment_Gateway. No per-endpoint nonces needed.
     *
     * i18n strings are identical to the native shell (orangepillNative.i18n) so
     * both frontends share the same translation strings.
     */
    public function get_payment_method_data() {
        $default_country = substr( get_option( 'woocommerce_default_country', 'CO' ), 0, 2 );

        return array(
            'title'       => $this->settings['title']       ?? __( 'Orangepill', 'orangepill-wc' ),
            'description' => $this->settings['description'] ?? '',
            'ajaxUrl'     => admin_url( 'admin-ajax.php' ),
            'nonce'       => wp_create_nonce( 'orangepill_wc_checkout' ),
            'currency'    => get_woocommerce_currency(),
            'country'     => $default_country,
            'isLoggedIn'  => is_user_logged_in(),
            'i18n'        => array(
                'loading_options'    => __( 'Loading payment options...', 'orangepill-wc' ),
                'select_method'      => __( 'Please select a payment method.', 'orangepill-wc' ),
                'creating_payment'   => __( 'Preparing payment...', 'orangepill-wc' ),
                'processing_payment' => __( 'Processing payment...', 'orangepill-wc' ),
                'payment_error'      => __( 'Payment could not be processed. Please try again.', 'orangepill-wc' ),
                'options_error'      => __( 'Unable to load payment options. Please refresh the page.', 'orangepill-wc' ),
                'no_methods'         => __( 'No payment methods are available for this order.', 'orangepill-wc' ),
                'speed_instant'      => __( 'Instant', 'orangepill-wc' ),
                'speed_same_day'     => __( 'Same day', 'orangepill-wc' ),
                'speed_next_day'     => __( 'Next day', 'orangepill-wc' ),
                'payment_key'        => __( 'Clave de pago', 'orangepill-wc' ),
                'copy'               => __( 'Copiar', 'orangepill-wc' ),
                'copied'             => __( 'Copiado', 'orangepill-wc' ),
                'expires_in'         => __( 'Expira en', 'orangepill-wc' ),
                'channel_qr'         => __( 'QR', 'orangepill-wc' ),
                'channel_reference'  => __( 'Llave Dinámica', 'orangepill-wc' ),
                'waiting_payment'    => __( 'Esperando confirmación del pago...', 'orangepill-wc' ),
                'payment_confirmed'  => __( '¡Pago confirmado!', 'orangepill-wc' ),
                'payment_expired'    => __( 'El tiempo para pagar ha expirado. Por favor intenta de nuevo.', 'orangepill-wc' ),
                'payment_failed'     => __( 'El pago no fue completado. Por favor intenta de nuevo.', 'orangepill-wc' ),
                'payment_timeout'    => __( 'Tiempo de espera agotado. Verifica tu email o intenta de nuevo.', 'orangepill-wc' ),
            ),
        );
    }
}
